Add new clipcli to seperate clipboard management from dmenu
cdown/clipmenu pull request #162
Opened 2021-03-26 18:06 UTC by simonhughcom

So this is my improved solution to a a problem I solved in #161 

I have added a new script called `clipcli` which handles the clipboard management.
It has 2 commands
- `clipcli list`: prints a list of clips.
- `clipcli get`: retrieves a clip based on its input.

So you can build your own scripts using `clipcli list | fzf | clipcli get`

I think this is a better solution because I believe that the clipboard management should be independent of whatever menu of fuzzy finder you use.

I have converted clipmenu to use the new script but kept the cli of clipmenu the same for backwards compatibility, but I think it may be a good idea to depreciate it and introduce separate scripts for dmenu, fzf, rofi etc

This would allow people to build their own scripts more easily, as a possible suggestion you could have a new dir in this repo or another repo with user scrips people can publish.

This was made in a bit of a rush, so I might have missed some things.

2021-12-08 14:56 UTC, cdown requested changes
Thanks for submitting, apologies for the delayed review. In general I think separating this is fine, but I'm a bit confused by some of the changes. Please also pass your changes through `shellcheck` and you'll see more of these issues ahead of time.

2021-12-08 14:56 UTC, cdown commented on clipcli
> +clipmenu is a simple clipboard manager using dmenu and xsel. Launch this
This help looks wrong to me, since it references clipmenu, no?

2021-12-08 14:56 UTC, cdown commented on clipcli
> +    if [[ -n $1 ]]; then
Just [[ $1 ]] is fine.

2021-12-08 14:56 UTC, cdown commented on clipcli
> +        read;
Why is there a semicolon here? :-)

2021-12-08 14:56 UTC, cdown commented on clipcli
> +        clip_line="$REPLY"
You can just do `read clip_line`. You'll also want to use `IFS= read -r`.

2021-12-08 14:56 UTC, cdown commented on clipcli
> +    list) list_clips; exit 0 ;;
Why explicit `exit 0`? Why not just preserve it?

2021-12-08 14:56 UTC, cdown commented on clipmenu
> +clip(){ clipcli get "$chosen_line"; }
`$chosen_line` comes implicitly, which makes this code hard to reason about for humans or static analysis. Just open code it.

2021-12-08 14:56 UTC, cdown commented on clipmenu
>  exit "${launcher_exit:-"$?"}"
Huh? You deleted `launcher_exit`, but it's still used

2021-12-08 14:56 UTC, cdown commented on clipcli
> +    # Not -h, see #142
Huh? It's right below

2022-02-03 00:41 UTC, nick87720z commented
Just curious, can't it be clipctl option, like `clipctl --stdin`, making it to perform commands from stdin? This would at least avoid duplication.

2022-02-03 08:20 UTC, nick87720z commented
My appologies - did not look commits before writing what I did before. Finally - what's really missing, but could be there.

I thought, clipcli takes commands from stdin coninuously, but it's not. Imho, persistant daemon would be useful, moreover it's shell script, whose runing creates significant overhead.

Also - the most effective way could be if actual job was done by `clipmenud`, providing named pipe to control itself (enable/disable commands could also use this interface). In this case there would be no possible race from different cli accessing cache - clipmenud would do everything.

2024-04-09 01:03 UTC, cdown commented
clipmenu is now in C, so closing since this applies to the old bash version. Thanks for your work on this, though!

2024-04-09 01:03 UTC, closed without merging